AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TinyURL:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'tinyurl.App::handleRequest'
      Runtime: java11
      CodeUri: TinyUrlFunction
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::764470733897:role/lambda-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: '/{tinyurl}'
            Method: GET
        Api3:
          Type: Api
          Properties:
            Path: /
            Method: GET
        Api4:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Tracing: Active
